### ISSUE TITLE
`module not found` message when applying a template

### ISSUE THREAD

**Issue by abelsromero** [walkmod/quickstart#1]
I did a clean installation, and then tried the commands as explained in http://walkmod.com/getstarted#templates.
But I get the following error:

```
: problems summary ::
:::: WARNINGS
        module not found: org.walkmod#walkmod-true-plugin;latest.integration
```

**Comment by rpau** [comment]
It was an error on the documentation. Now it is fixed. Instead of:
walkmod add --isMergeable=true --name=jpa-id -Dtemplates="[\"src/main/walkmod/templates/jpa-id.groovy\"]" template

Must be:

walkmod add --isMergeable --name=jpa-id -Dtemplates="[\"src/main/walkmod/templates/jpa-id.groovy\"]" template

Thank you Abel :)
